<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{439a731e-10f6-437d-9e9f-b6ea22b9e972}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// (C) Jouni Könönen
	//	31.3.2024
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[StateMachine();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>