<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ControlPanel" Id="{6fafcdca-fd53-44b1-8233-794b801bcaa5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ControlPanel
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bAtBufferEntry	:	BOOL;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[{region "READ Values from Sensors"}
	bAtBufferEntry	:=	GVL.mb_Output_Coils[0];
		 
		 
{endregion}]]></ST>
    </Implementation>
    <LineIds Name="ControlPanel">
      <LineId Id="9" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>