<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ConveyorSequence" Id="{6e3cb253-5875-4dbd-bea9-f9128d87fc83}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ConveyorSequence
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ConveyorSequence">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>